<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="test" Id="{041284d1-4032-4a04-9824-3e720f32b5ff}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM test
VAR
	xTestInput	AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="test">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>