<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{4d55c260-25ae-4664-9203-47957f836f1e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	arrInputPNP AT %I* : ARRAY[0..GVL.cuiNrChannel] OF BOOL;
	arrInputNPN	AT %I* : ARRAY[0..GVL.cuiNrChannel] OF BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[arrInputPNP;
arrInputNPN;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>